### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by jimmymonet** [ieuanmeredith/Sim-Stat-Tracker#1]
I tried multiple times to connect to my iRacing account with this tool and it never syncs. I just see the logo spin and spin, I've left this running a couple of times for over an hour and still it doesn't sync. I'm not sure if there is a log somewhere to get any additional details.

**Comment by ieuanmeredith** [comment]
Sorry, I hadn't seen this until now. I have checked and can see that I'm getting the same issue at the moment. I'll look into it

**Comment by ieuanmeredith** [comment]
Ok so I've found that iRacing have changed something with how results are fetched, should be a pretty straight forward fix I think

**Comment by jimmymonet** [comment]
I hope it's an easy fix for you. I appreciate you taking the time to work
on it.

**Comment by ieuanmeredith** [comment]
Just building a release with the fix. Previously I needed to batch call results because of poor performance on iRacings side.

They've made some API changes recently that were now returning an error on the batch calls I was making, so I just changed it to get all results in 1 call.

I think the performance increases they have made recently should prevent this call from timing out like it was in the past 🤞 

Fixed in https://github.com/ieuanmeredith/Sim-Stat-Tracker/commit/14a6dae01f161cce99409b519e74f32d2d6703cf
